# Netlify configuration file
# This provides additional configuration beyond _redirects

[build]
  # No build command needed for static files
  command = ""
  # Publish from root directory
  publish = "."

[build.environment]
  # Environment variables (if needed)
  NODE_VERSION = "18"

[[headers]]
  # Apply headers to all files
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # PWA and caching headers
    Cache-Control = "public, max-age=3600"

[[headers]]
  # Specific headers for service worker
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  # Headers for manifest
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  # Long cache for static assets
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Edge redirects (faster than _redirects file)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "editor"], Country = ["!US"]}

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
